version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: order_cuisine
    restart: always
    volumes:
      - .:/var/www/html
    depends_on:
      - postgres
    networks:
      - laravel_network
    entrypoint: ["/bin/sh", "./docker-entrypoint.sh"]
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: cuisine
    ports:
      - "5432:5432"
    volumes:
      - /etc/postgres/data:/var/lib/postgresql/data
    networks:
      - laravel_network
  nginx:
    image: nginx:latest
    container_name: nginx_server
    restart: always
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certificate.pem:/etc/nginx/ssl/certificate.pem
      - ./nginx/private_key.key:/etc/nginx/ssl/private_key.key
    depends_on:
      - app
    networks:
      - laravel_network
networks:
  laravel_network:
    driver: bridge
